import { toNumber } from './ct600.js';

/**
 * Corporation Tax Online (CTO) XML submission builder.
 *
 * Generates the GovTalk envelope + IRenvelope that Corporation Tax Online
 * accepts TODAY for filing a CT600 (schema namespace
 * http://www.govtalk.gov.uk/taxation/CT/5, schema version 2022-v1.99,
 * top element CompanyTaxReturn). The element structure mirrors the official
 * HMRC "CT600 valid sample: no attachments" (v3) publication byte-for-byte
 * in the fixed parts:
 *   https://www.gov.uk/government/publications/corporation-tax-technical-specifications-ct600-valid-xml-samples
 *
 * Who this is for: the accountant's filing software (IRIS/Digita/TaxCalc)
 * consumes this XML as the pre-filled CT600. The figures come from the
 * provision result; SenderID / vendor ChannelRouting and the IRmark must be
 * filled in by the filing software before submission. Marginal relief (box 14)
 * is emitted under CorporationTaxChargeable.MarginalRelief when non-zero,
 * alongside the split tax at 19% and 25% bands.
 */

export const GOVTALK_NS = 'http://www.govtalk.gov.uk/CM/envelope';
export const CT_NS = 'http://www.govtalk.gov.uk/taxation/CT/5';
export const CT_SCHEMA_VERSION = '2022-v1.99';

export interface CtOnlineSubmissionInput {
  utr: string;
  companyName: string;
  registrationNumber: string; // Companies House number
  periodStart: string;
  periodEnd: string;
  companyType: string;        // schema code, e.g. '6' (private company limited by shares)
  turnover: number;
  chargeableProfits: number;  // taxable total profits
  taxAtMainRate: number;
  taxAtSmallProfitsRate: number;
  marginalRelief: number;
  taxPayable: number;
  gatewayTest?: boolean;      // 1 = test environment
  senderId?: string;
  vendorId?: string;
  product?: string;
  productVersion?: string;
}

export interface CtOnlineSubmission {
  contentType: 'text/xml';
  filename: string;
  envelopeVersion: string;
  schemaVersion: string;
  xml: string;
}

const ESC_RE = /[&<>"']/g;
const ESC_MAP: Record<string, string> = { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&apos;' };
const esc = (s: string) => s.replace(ESC_RE, ch => ESC_MAP[ch]);

export function buildCtOnlineSubmission(input: CtOnlineSubmissionInput): CtOnlineSubmission {
  validate(input);
  const utr = input.utr;
  const test = input.gatewayTest ?? true;
  const taxCharge = round2(Math.max(0, input.taxAtMainRate + input.taxAtSmallProfitsRate - input.marginalRelief));
  const smallProfitsYear = Number(input.periodEnd.slice(0, 4)) - 1;
  const mainRateYear = Number(input.periodEnd.slice(0, 4)) - 1;

  const financialYears: string[] = [];
  if (input.taxAtSmallProfitsRate > 0) {
    financialYears.push(fyBlock(smallProfitsYear, 19, input.taxAtSmallProfitsRate));
  }
  if (input.taxAtMainRate > 0) {
    financialYears.push(fyBlock(mainRateYear, 25, input.taxAtMainRate));
  }
  if (financialYears.length === 0) {
    financialYears.push(fyBlock(mainRateYear, 25, 0));
  }

  const marginalRelief = input.marginalRelief > 0
    ? `\t\t\t\t<MarginalRelief>${input.marginalRelief.toFixed(2)}</MarginalRelief>\n`
    : '';

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by TaxPro from a provision result. Figures follow the official CT600 valid XML sample (v3). -->
<GovTalkMessage xmlns="${GOVTALK_NS}" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
\t<EnvelopeVersion>2.0</EnvelopeVersion>
\t<Header>
\t\t<MessageDetails>
\t\t\t<Class>HMRC-CT-CT600</Class>
\t\t\t<Qualifier>request</Qualifier>
\t\t\t<Function>submit</Function>
\t\t\t<CorrelationID/>
\t\t\t<Transformation>XML</Transformation>
\t\t\t<GatewayTest>${test ? '1' : '0'}</GatewayTest>
\t\t</MessageDetails>
\t\t<SenderDetails>
\t\t\t<IDAuthentication>
\t\t\t\t<SenderID>${esc(input.senderId ?? 'Provided by the SDST')}</SenderID>
\t\t\t\t<Authentication>
\t\t\t\t\t<Method>clear</Method>
\t\t\t\t\t<Role>Principal</Role>
\t\t\t\t\t<Value>${esc(input.senderId ?? 'Provided by the SDST')}</Value>
\t\t\t\t</Authentication>
\t\t\t</IDAuthentication>
\t\t</SenderDetails>
\t</Header>
\t<GovTalkDetails>
\t\t<Keys>
\t\t\t<Key Type="UTR">${utr}</Key>
\t\t</Keys>
\t\t<TargetDetails>
\t\t\t<Organisation>HMRC</Organisation>
\t\t</TargetDetails>
\t\t<ChannelRouting>
\t\t\t<Channel>
\t\t\t\t<URI>${esc(input.vendorId ?? 'Enter your 4 digit vendor ID')}</URI>
\t\t\t\t<Product>${esc(input.product ?? 'TaxPro')}</Product>
\t\t\t\t<Version>${esc(input.productVersion ?? '0.1.0')}</Version>
\t\t\t</Channel>
\t\t</ChannelRouting>
\t</GovTalkDetails>
\t<Body>
\t\t<IRenvelope xmlns="${CT_NS}">
\t\t\t<IRheader>
\t\t\t\t<Keys>
\t\t\t\t\t<Key Type="UTR">${utr}</Key>
\t\t\t\t</Keys>
\t\t\t\t<PeriodEnd>${input.periodEnd}</PeriodEnd>
\t\t\t\t<DefaultCurrency>GBP</DefaultCurrency>
\t\t\t\t<Manifest>
\t\t\t\t\t<Contains>
\t\t\t\t\t\t<Reference>
\t\t\t\t\t\t\t<Namespace>${CT_NS}</Namespace>
\t\t\t\t\t\t\t<SchemaVersion>${CT_SCHEMA_VERSION}</SchemaVersion>
\t\t\t\t\t\t\t<TopElementName>CompanyTaxReturn</TopElementName>
\t\t\t\t\t\t</Reference>
\t\t\t\t\t</Contains>
\t\t\t\t</Manifest>
\t\t\t\t<IRmark Type="generic">Enter IRmark here</IRmark>
\t\t\t\t<Sender>Company</Sender>
\t\t\t</IRheader>
\t\t\t<CompanyTaxReturn ReturnType="new">
\t\t\t\t<CompanyInformation>
\t\t\t\t\t<CompanyName>${esc(input.companyName)}</CompanyName>
\t\t\t\t\t<RegistrationNumber>${esc(input.registrationNumber)}</RegistrationNumber>
\t\t\t\t\t<Reference>${utr}</Reference>
\t\t\t\t\t<CompanyType>${esc(input.companyType)}</CompanyType>
\t\t\t\t\t<PeriodCovered>
\t\t\t\t\t\t<From>${input.periodStart}</From>
\t\t\t\t\t\t<To>${input.periodEnd}</To>
\t\t\t\t\t</PeriodCovered>
\t\t\t\t</CompanyInformation>
\t\t\t\t<Turnover>
\t\t\t\t\t<Total>${input.turnover.toFixed(2)}</Total>
\t\t\t\t</Turnover>
\t\t\t\t<CompanyTaxCalculation>
\t\t\t\t\t<ChargeableProfits>${input.chargeableProfits.toFixed(2)}</ChargeableProfits>
\t\t\t\t\t<CorporationTaxChargeable>
${financialYears.join('')}
${marginalRelief}${marginalRelief ? '' : '\t\t\t\t'}
\t\t\t\t\t</CorporationTaxChargeable>
\t\t\t\t\t<CorporationTax>${taxCharge.toFixed(2)}</CorporationTax>
\t\t\t\t\t<NetCorporationTaxChargeable>${taxCharge.toFixed(2)}</NetCorporationTaxChargeable>
\t\t\t\t\t<TaxReliefsAndDeductions>
\t\t\t\t\t\t<TotalReliefsAndDeductions>0.00</TotalReliefsAndDeductions>
\t\t\t\t\t</TaxReliefsAndDeductions>
\t\t\t\t</CompanyTaxCalculation>
\t\t\t\t<CalculationOfTaxOutstandingOrOverpaid>
\t\t\t\t\t<NetCorporationTaxLiability>${taxCharge.toFixed(2)}</NetCorporationTaxLiability>
\t\t\t\t\t<TaxChargeable>${taxCharge.toFixed(2)}</TaxChargeable>
\t\t\t\t\t<TaxPayable>${round2(input.taxPayable).toFixed(2)}</TaxPayable>
\t\t\t\t</CalculationOfTaxOutstandingOrOverpaid>
\t\t\t\t<Declaration>
\t\t\t\t\t<AcceptDeclaration>no</AcceptDeclaration>
\t\t\t\t\t<Name>${esc(input.companyName)}</Name>
\t\t\t\t\t<Status>In progress</Status>
\t\t\t\t</Declaration>
\t\t\t</CompanyTaxReturn>
\t\t</IRenvelope>
\t</Body>
</GovTalkMessage>`;

  return {
    contentType: 'text/xml',
    filename: `taxpro-ct600-${input.periodEnd}.xml`,
    envelopeVersion: '2.0',
    schemaVersion: CT_SCHEMA_VERSION,
    xml,
  };
}

function fyBlock(year: number, rate: number, tax: number): string {
  return `\t\t\t\t\t<FinancialYearOne>
\t\t\t\t\t\t<Year>${year}</Year>
\t\t\t\t\t\t<Details>
\t\t\t\t\t\t\t<TaxRate>${rate.toFixed(2)}</TaxRate>
\t\t\t\t\t\t\t<Tax>${round2(tax).toFixed(2)}</Tax>
\t\t\t\t\t\t</Details>
\t\t\t\t\t</FinancialYearOne>`;
}

function validate(input: CtOnlineSubmissionInput) {
  if (!/^\d{10}$/.test(input.utr)) throw new Error('UTR must be 10 digits');
  if (!input.registrationNumber) throw new Error('Companies House registration number is required');
  if (!input.periodStart || !input.periodEnd) throw new Error('Accounting period is required');
  if (input.chargeableProfits < 0) throw new Error('chargeable profits cannot be negative');
  if (input.marginalRelief < 0) throw new Error('marginal relief cannot be negative');
}

function round2(n: number) {
  return Math.round(n * 100) / 100;
}

/** Convenience: build from a CT600 return object. */
export function ctoFromCt600(ct600: {
  company: { companyName: string; utr: string; companiesHouseNumber?: string };
  period: { start: string; end: string };
  computed: { totalTaxCharge: number; taxPayable: number };
  boxes: Array<{ box: number; name: string; value: string | number }>;
}, opts?: Partial<CtOnlineSubmissionInput>): CtOnlineSubmission {
  const box = (n: number) => toNumber(ct600.boxes.find(b => b.box === n)?.value);
  return buildCtOnlineSubmission({
    utr: ct600.company.utr,
    companyName: ct600.company.companyName,
    registrationNumber: ct600.company.companiesHouseNumber ?? '00000000',
    periodStart: ct600.period.start,
    periodEnd: ct600.period.end,
    companyType: '6',
    turnover: box(5),
    chargeableProfits: box(10),
    taxAtMainRate: box(12),
    taxAtSmallProfitsRate: box(13),
    marginalRelief: box(14),
    taxPayable: ct600.computed.taxPayable,
    ...opts,
  });
}
