/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as MappingRouteImport } from './routes/mapping'
import { Route as ProvisionRouteImport } from './routes/provision'
import { Route as ReviewRouteImport } from './routes/review'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const MappingRoute = MappingRouteImport.update({
  id: '/mapping',
  path: '/mapping',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvisionRoute = ProvisionRouteImport.update({
  id: '/provision',
  path: '/provision',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connections': typeof ConnectionsRoute
  '/mapping': typeof MappingRoute
  '/provision': typeof ProvisionRoute
  '/review': typeof ReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connections': typeof ConnectionsRoute
  '/mapping': typeof MappingRoute
  '/provision': typeof ProvisionRoute
  '/review': typeof ReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connections': typeof ConnectionsRoute
  '/mapping': typeof MappingRoute
  '/provision': typeof ProvisionRoute
  '/review': typeof ReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/connections' | '/mapping' | '/provision' | '/review'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/connections' | '/mapping' | '/provision' | '/review'
  id: '__root__' | '/' | '/connections' | '/mapping' | '/provision' | '/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectionsRoute: typeof ConnectionsRoute
  MappingRoute: typeof MappingRoute
  ProvisionRoute: typeof ProvisionRoute
  ReviewRoute: typeof ReviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapping': {
      id: '/mapping'
      path: '/mapping'
      fullPath: '/mapping'
      preLoaderRoute: typeof MappingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provision': {
      id: '/provision'
      path: '/provision'
      fullPath: '/provision'
      preLoaderRoute: typeof ProvisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectionsRoute: ConnectionsRoute,
  MappingRoute: MappingRoute,
  ProvisionRoute: ProvisionRoute,
  ReviewRoute: ReviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
